"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [3, 4, 8]

[preview]
max_width = 1600
max_height = 1600


[opener]
edit = [
  { run = "${EDITOR:-nvim} %s", desc = "edit", for = "unix", block = true },
]
open = [
  { run = 'open "$@"', desc = "open", for = "unix", orphan = true },
]

[[plugin.prepend_previewers]]
url = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w "$1"'
[[plugin.prepend_previewers]]
url = "*/"
run = 'piper -- eza -TL=2 --color=always --icons=always --group-directories-first --no-quotes "$1"'
